### ISSUE TITLE
Komentáre

### ISSUE THREAD

**Issue by ghost** [Kazarr/KrosDotaznik#18]
Píšte komentáre. Na konci bude neskoro :) Pri commitovaní nemusíte, ale pri pushi by malo byť všetko, čo pushujete, dobre okomentované (stačí polia, vlastnosti a metódy, vnútri v metódach iba v nevyhnutnom prípade).

**Comment by Kazarr** [comment]
Niečo som okomentoval. Budeme sa snažiť ďalej komentovať ale teraz túto issue uzavrem
