### ISSUE TITLE
FileService

### ISSUE THREAD

**Issue by ghost** [Kazarr/KrosDotaznik#44]
V LoadJson pre istotu tiež nastavte Encoding.

A zdá sa mi to, alebo spolu so zašifrovanými heslami ukladáte aj kľúč a inicializačný vektor? :open_mouth: Ak áno, určite to tak nerobte :) Dá sa to riešiť inak. Napríklad si urobíte len jedno dlhé pole bytov, v ktorom na začiatku bude prvá polka kľúča, potom bude IV, potom druhá polka kľúča a potom samotné dáta (alebo niečo na ten štýl). Aby prípadnému "útočníkovi" nestačilo len ukradnúť dáta a vie dešifrovať.

**Comment by Kazarr** [comment]
Zacryptuje sa to pomocou konštatného pola byte-ov a konštantného IV.
Takisto sa to aj decryptuje pomocou tých dvoch premenných
