### ISSUE TITLE
Connection string

### ISSUE THREAD

**Issue by ghost** [Kazarr/KrosDotaznik#47]
V ConnectionString nemusíte špecifikovať System Database. To sa používa iba ak by ste chceli zabezpečiť DB pomocou nastavenia workgroup.

**Comment by cvirec1** [comment]
Keď to dám bez toho tam mi to padá na chybe. Zrejme to je preto lebo na Cenkrose využívame system.mdw a mam tak nastavení môj access. S takýmto connection to funguje aj u mňa a u kuba, ktorý nemá nastavený v access system.mdw
